name: grocery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  flutter_iconly: ^1.0.2
  card_swiper: ^3.0.1
  fancy_shimmer_image: ^2.0.2
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  uuid: ^4.4.0
  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cat/
    - assets/images/landing/
    - assets/images/offres/